const express = require('express');
const router = express.Router();
const prizeController = require('../controllers/prizeController');
const authMiddleware = require('../middleware/auth');
const { requirePermission, PERMISSIONS } = require('../middleware/permissions');
const asyncHandler = require('../utils/asyncHandler');

router.use('/admin', authMiddleware, requirePermission(PERMISSIONS.PRIZE_MANAGE));
router.get('/admin/items', asyncHandler(prizeController.getAdminItems));
router.post('/admin/items', asyncHandler(prizeController.createAdminItem));
router.put('/admin/items/order', asyncHandler(prizeController.updateAdminItemOrder));
router.put('/admin/items/:id', asyncHandler(prizeController.updateAdminItem));
router.delete('/admin/items/:id', asyncHandler(prizeController.deleteAdminItem));
router.post('/admin/items/:id/images', asyncHandler(prizeController.uploadAdminImages));
router.put('/admin/items/:id/images/order', asyncHandler(prizeController.updateAdminImageOrder));
router.delete('/admin/items/:id/images/:imageId', asyncHandler(prizeController.deleteAdminImage));
router.get('/admin/orders', asyncHandler(prizeController.getAdminPrizeOrders));
router.get('/admin/orders/:id', asyncHandler(prizeController.getAdminPrizeOrderById));
router.put('/admin/orders/:id/status', asyncHandler(prizeController.updateAdminPrizeOrderStatus));
router.get('/admin/redemptions', asyncHandler(prizeController.getAdminRedemptions));
router.put('/admin/redemptions/:id/status', asyncHandler(prizeController.updateAdminRedemptionStatus));

router.get('/user/orders', authMiddleware, asyncHandler(prizeController.getUserPrizeOrders));
router.get('/user/orders/:id', authMiddleware, asyncHandler(prizeController.getUserPrizeOrderById));
router.get('/user/redemptions', authMiddleware, asyncHandler(prizeController.getUserRedemptions));
router.get('/shipping-addresses', authMiddleware, asyncHandler(prizeController.getShippingAddresses));
router.post('/shipping-addresses', authMiddleware, asyncHandler(prizeController.createShippingAddress));
router.put('/shipping-addresses/:id', authMiddleware, asyncHandler(prizeController.updateShippingAddress));
router.put('/shipping-addresses/:id/default', authMiddleware, asyncHandler(prizeController.setDefaultShippingAddress));
router.delete('/shipping-addresses/:id', authMiddleware, asyncHandler(prizeController.deleteShippingAddress));
router.get('/cart', authMiddleware, asyncHandler(prizeController.getCart));
router.post('/cart/items', authMiddleware, asyncHandler(prizeController.addCartItem));
router.put('/cart/items/:id', authMiddleware, asyncHandler(prizeController.updateCartItem));
router.delete('/cart/items/:id', authMiddleware, asyncHandler(prizeController.deleteCartItem));
router.delete('/cart', authMiddleware, asyncHandler(prizeController.clearCart));
router.post('/cart/checkout', authMiddleware, asyncHandler(prizeController.checkoutCart));
router.post('/redeem', authMiddleware, asyncHandler(prizeController.redeemPrize));
router.get('/', asyncHandler(prizeController.getAllPrizes));
router.get('/:id', asyncHandler(prizeController.getPrizeById));

module.exports = router;
